import { beforeAll,describe,expect,it } from 'vitest';
import request from 'supertest';
import { createApp } from '../src/app.js';
import { seed } from '../src/seed/index.js';
const app=createApp();let resident='',coordinator='',responder='';
async function login(email:string){return (await request(app).post('/api/auth/login').send({email,password:'Demo123!'})).body.data.accessToken;}
beforeAll(async()=>{await seed();resident=await login('resident@rescuermap.local');coordinator=await login('coordinator@rescuermap.local');responder=await login('responder@rescuermap.local');});
describe('API rescue workflow',()=>{
  it('serves the local test console',async()=>{const page=await request(app).get('/');expect(page.status).toBe(200);expect(page.text).toContain('RescuerMap Test Console');});
  it('protects coordinator resources',async()=>{expect((await request(app).get('/api/admin/dashboard').set('Authorization',`Bearer ${resident}`)).status).toBe(403);});
  it('runs need-help through safe and closed with audit',async()=>{const created=await request(app).post('/api/help-requests').set('Authorization',`Bearer ${resident}`).send({clientRequestId:'test-happy-path',incidentId:'inc_demo',latitude:12.892,longitude:77.602,category:'MEDICAL',description:'Test emergency',peopleCount:1,medicalEmergency:true,vulnerabilities:['ELDERLY'],immediateDanger:true});expect(created.status).toBe(201);const requestId=created.body.data.id;expect(created.body.data.priority_score).toBeGreaterThan(50);const duplicate=await request(app).post('/api/help-requests').set('Authorization',`Bearer ${resident}`).send({clientRequestId:'test-happy-path',incidentId:'inc_demo',latitude:12.892,longitude:77.602,category:'MEDICAL',peopleCount:1,medicalEmergency:true,vulnerabilities:[],immediateDanger:true});expect(duplicate.body.data.id).toBe(requestId);const matches=await request(app).get(`/api/matches/${requestId}`).set('Authorization',`Bearer ${coordinator}`);expect(matches.body.data.length).toBeGreaterThan(0);const assigned=await request(app).post('/api/assignments').set('Authorization',`Bearer ${coordinator}`).send({requestId,responderId:'rsp_demo'});expect(assigned.status).toBe(201);const assignmentId=assigned.body.data.id;for(const status of ['ACCEPTED','EN_ROUTE','ARRIVED','ASSISTING','EVACUATED','SHELTER_CHECKIN','SAFE','CLOSED']){const changed=await request(app).post(`/api/assignments/${assignmentId}/transition`).set('Authorization',`Bearer ${status==='CLOSED'?coordinator:responder}`).send({status});expect(changed.status,`${status}: ${JSON.stringify(changed.body)}`).toBe(200);}const timeline=await request(app).get(`/api/audit/timeline/${requestId}`).set('Authorization',`Bearer ${coordinator}`);expect(timeline.body.data.map((x:any)=>x.action)).toEqual(expect.arrayContaining(['HELP_REQUEST_CREATED','RESPONDER_ASSIGNED','ASSIGNMENT_ACCEPTED','RESPONDER_EN_ROUTE','RESPONDER_ARRIVED','PERSON_EVACUATED','SHELTER_CHECKIN','PERSON_SAFE','CASE_CLOSED']));});
  it('drives the provider-backed simulator',async()=>{const started=await request(app).post('/api/simulator/start').set('Authorization',`Bearer ${coordinator}`).send({responders:1,reports:1});expect(started.status).toBe(201);const critical=await request(app).post('/api/simulator/control').set('Authorization',`Bearer ${coordinator}`).send({action:'TRIGGER_CRITICAL_STATE'});expect(critical.status).toBe(200);const incident=await request(app).get(`/api/incidents/${started.body.data.incidentId}`).set('Authorization',`Bearer ${coordinator}`);expect(incident.body.data.severity_level).toBe('CRITICAL');});
});
