import { Router } from 'express';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import { z } from 'zod';
import { config } from '../config/index.js';
import { db } from '../db/index.js';
import { auth, roles } from '../middleware/auth.js';
import { asyncRoute } from '../middleware/errors.js';
import { audit } from '../services/audit.js';
import { createGeofenceAlerts, createHelpRequest, getMatches, notify, recommendEscalation, recomputeSeverity, transitionAssignment } from '../services/operations.js';
import { emit } from '../services/runtime.js';
import { id, now, parseJson } from '../utils/core.js';
import { providers } from '../integrations/providers/index.js';
import { simulatorControl, simulatorStart } from '../services/simulator.js';

const r=Router(); const ok=(res:any,data:any,status=200)=>res.status(status).json({success:true,data});
const credentials=z.object({email:z.email(),password:z.string().min(8)});
const locationSchema=z.object({latitude:z.number().min(-90).max(90),longitude:z.number().min(-180).max(180),accuracy:z.number().nonnegative().optional(),source:z.enum(['GPS','NETWORK','MANUAL','SIMULATED']).default('GPS'),sharingState:z.enum(['SHARED','NOT_SHARED']).default('SHARED'),incidentId:z.string().optional(),assignmentId:z.string().optional()});
const helpSchema=z.object({clientRequestId:z.string().max(100).optional(),incidentId:z.string(),latitude:z.number().min(-90).max(90),longitude:z.number().min(-180).max(180),category:z.enum(['EVACUATION','MEDICAL','STRANDED','ELDERLY_ASSISTANCE','DISABILITY_ASSISTANCE','CHILD_FAMILY_ASSISTANCE','TRANSPORTATION','OTHER']),description:z.string().max(1000).optional(),peopleCount:z.number().int().min(1).max(100).default(1),medicalEmergency:z.boolean().default(false),vulnerabilities:z.array(z.string().max(80)).max(10).default([]),immediateDanger:z.boolean().default(false)});

r.post('/auth/register',asyncRoute(async(req:any,res:any)=>{const b=credentials.extend({name:z.string().min(1).max(120),role:z.enum(['RESIDENT','RESPONDER']).default('RESIDENT')}).parse(req.body);const t=now(),u={id:id('usr'),email:b.email.toLowerCase(),password_hash:await bcrypt.hash(b.password,12),name:b.name,role:b.role,status:'ACTIVE',verification_status:b.role==='RESIDENT'?'VERIFIED':'PENDING',created_at:t,updated_at:t};try{db().prepare('INSERT INTO users(id,email,password_hash,name,role,status,verification_status,created_at,updated_at) VALUES(@id,@email,@password_hash,@name,@role,@status,@verification_status,@created_at,@updated_at)').run(u);}catch(e:any){if(e.code==='SQLITE_CONSTRAINT_UNIQUE')throw Object.assign(new Error('Email already registered'),{status:409});throw e;}if(b.role==='RESPONDER')db().prepare("INSERT INTO responders(id,user_id,verification_status,status,updated_at) VALUES(?,?,?,'OFFLINE',?)").run(id('rsp'),u.id,'PENDING',t);audit('USER_REGISTERED',{actorId:u.id,metadata:{role:u.role}});ok(res,{id:u.id,email:u.email,name:u.name,role:u.role,verificationStatus:u.verification_status},201);}));
r.post('/auth/login',asyncRoute(async(req:any,res:any)=>{const b=credentials.parse(req.body);const u=db().prepare('SELECT * FROM users WHERE email=?').get(b.email.toLowerCase()) as any;if(!u||!(await bcrypt.compare(b.password,u.password_hash)))throw Object.assign(new Error('Invalid credentials'),{status:401});if(u.status!=='ACTIVE')throw Object.assign(new Error('Account unavailable'),{status:403});const token=jwt.sign({id:u.id,role:u.role,tokenVersion:u.token_version},config.jwtSecret,{expiresIn:config.jwtExpiresIn as any});audit('AUTH_LOGIN',{actorId:u.id});ok(res,{accessToken:token,tokenType:'Bearer',expiresIn:config.jwtExpiresIn,user:{id:u.id,name:u.name,email:u.email,role:u.role,verificationStatus:u.verification_status}});}));
r.post('/auth/logout',auth,(req,res)=>{db().prepare('UPDATE users SET token_version=token_version+1,updated_at=? WHERE id=?').run(now(),req.user!.id);audit('AUTH_LOGOUT',{actorId:req.user!.id});ok(res,{loggedOut:true});});

r.get('/users/me',auth,(req,res)=>ok(res,db().prepare('SELECT id,email,name,phone,role,status,verification_status,alerts_opt_in,operational_status,created_at,updated_at FROM users WHERE id=?').get(req.user!.id)));
r.patch('/users/:id',auth,(req,res)=>{if(req.user!.id!==req.params.id&&!['ADMIN'].includes(req.user!.role))return res.status(403).json({success:false,error:{code:'FORBIDDEN',message:'Cannot edit another user'}});const b=z.object({name:z.string().min(1).max(120).optional(),phone:z.string().max(30).nullable().optional(),alertsOptIn:z.boolean().optional(),status:z.enum(['ACTIVE','SUSPENDED','DISABLED']).optional(),verificationStatus:z.enum(['UNVERIFIED','PENDING','VERIFIED','REJECTED']).optional()}).parse(req.body);if((b.status||b.verificationStatus)&&req.user!.role!=='ADMIN')return res.status(403).json({success:false,error:{code:'FORBIDDEN',message:'Admin access required'}});const current=db().prepare('SELECT * FROM users WHERE id=?').get(req.params.id) as any;if(!current)return res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'User not found'}});db().prepare('UPDATE users SET name=?,phone=?,alerts_opt_in=?,status=?,verification_status=?,updated_at=? WHERE id=?').run(b.name??current.name,b.phone===undefined?current.phone:b.phone,b.alertsOptIn===undefined?current.alerts_opt_in:+b.alertsOptIn,b.status??current.status,b.verificationStatus??current.verification_status,now(),current.id);ok(res,db().prepare('SELECT id,email,name,phone,role,status,verification_status,alerts_opt_in,operational_status FROM users WHERE id=?').get(current.id));});
r.get('/users',auth,roles('COORDINATOR','ADMIN'),(_req,res)=>ok(res,db().prepare('SELECT id,email,name,role,status,verification_status,operational_status,created_at FROM users').all()));

r.post('/locations',auth,(req,res)=>{const b=locationSchema.parse(req.body),t=now(),state=b.sharingState==='NOT_SHARED'?'NOT_SHARED':b.accuracy&&b.accuracy>100?'STALE':'AVAILABLE';const l={id:id('loc'),user_id:req.user!.id,incident_id:b.incidentId||null,assignment_id:b.assignmentId||null,latitude:b.latitude,longitude:b.longitude,accuracy:b.accuracy??null,source:b.source,sharing_state:b.sharingState,state,recorded_at:t};db().prepare('INSERT INTO locations VALUES(@id,@user_id,@incident_id,@assignment_id,@latitude,@longitude,@accuracy,@source,@sharing_state,@state,@recorded_at)').run(l);emit('responder.location_updated',{userId:req.user!.id,incidentId:b.incidentId,latitude:b.latitude,longitude:b.longitude,accuracy:b.accuracy,recordedAt:t},b.incidentId?`incident:${b.incidentId}`:undefined);ok(res,l,201);});
r.get('/locations/users/:userId/latest',auth,(req,res)=>{if(req.user!.id!==req.params.userId&&!['COORDINATOR','ADMIN'].includes(req.user!.role))return res.status(403).json({success:false,error:{code:'LOCATION_PRIVATE',message:'Exact location access denied'}});const l=db().prepare('SELECT * FROM locations WHERE user_id=? ORDER BY recorded_at DESC LIMIT 1').get(req.params.userId);if(!l)return res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'Location unavailable'}});ok(res,l);});
r.get('/locations/users/:userId/history',auth,roles('COORDINATOR','ADMIN'),(req,res)=>ok(res,db().prepare('SELECT * FROM locations WHERE user_id=? AND incident_id=? ORDER BY recorded_at DESC LIMIT 500').all(req.params.userId,req.query.incidentId)));

r.get('/incidents',auth,(req,res)=>ok(res,db().prepare(`SELECT * FROM incidents ${req.query.status?'WHERE status=?':''} ORDER BY updated_at DESC`).all(...(req.query.status?[req.query.status]:[])).map(hydrateIncident)));
r.post('/incidents',auth,roles('COORDINATOR','ADMIN'),(req,res)=>{const b=z.object({disasterType:z.string().default('WILDFIRE'),name:z.string().min(1),description:z.string().optional(),latitude:z.number(),longitude:z.number(),radiusKm:z.number().positive().default(1),spreadDirection:z.number().optional(),spreadSpeed:z.number().nonnegative().optional(),status:z.enum(['DETECTED','ACTIVE','CONTAINED','RESOLVED','CLOSED']).default('DETECTED'),sourceType:z.enum(['OFFICIAL','COMMUNITY','SYSTEM_GENERATED','SIMULATED']).default('SYSTEM_GENERATED')}).parse(req.body);const t=now(),i={id:id('inc'),disaster_type:b.disasterType,name:b.name,description:b.description||null,latitude:b.latitude,longitude:b.longitude,radius_km:b.radiusKm,boundary_json:null,spread_direction:b.spreadDirection??null,spread_speed:b.spreadSpeed??null,start_time:t,status:b.status,severity_score:0,severity_level:'LOW',severity_factors:'{}',severity_reasons:'[]',source_type:b.sourceType,created_at:t,updated_at:t};db().prepare('INSERT INTO incidents VALUES(@id,@disaster_type,@name,@description,@latitude,@longitude,@radius_km,@boundary_json,@spread_direction,@spread_speed,@start_time,@status,@severity_score,@severity_level,@severity_factors,@severity_reasons,@source_type,@created_at,@updated_at)').run(i);audit('INCIDENT_CREATED',{incidentId:i.id,actorId:req.user!.id,newState:i.status});ok(res,hydrateIncident(i),201);});
r.get('/incidents/:id',(req,res,next)=>auth(req,res,()=>{const i=db().prepare('SELECT * FROM incidents WHERE id=?').get(req.params.id);i?ok(res,hydrateIncident(i)):res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'Incident not found'}});}));
r.patch('/incidents/:id',auth,roles('COORDINATOR','ADMIN'),(req,res)=>{const old=db().prepare('SELECT * FROM incidents WHERE id=?').get(req.params.id) as any;if(!old)return res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'Incident not found'}});const b=z.object({name:z.string().optional(),description:z.string().optional(),radiusKm:z.number().positive().optional(),spreadDirection:z.number().optional(),spreadSpeed:z.number().nonnegative().optional(),status:z.enum(['DETECTED','ACTIVE','CONTAINED','RESOLVED','CLOSED']).optional()}).parse(req.body);db().prepare('UPDATE incidents SET name=?,description=?,radius_km=?,spread_direction=?,spread_speed=?,status=?,updated_at=? WHERE id=?').run(b.name??old.name,b.description??old.description,b.radiusKm??old.radius_km,b.spreadDirection??old.spread_direction,b.spreadSpeed??old.spread_speed,b.status??old.status,now(),old.id);audit('INCIDENT_UPDATED',{incidentId:old.id,actorId:req.user!.id,previousState:old.status,newState:b.status??old.status});ok(res,hydrateIncident(db().prepare('SELECT * FROM incidents WHERE id=?').get(old.id)));});
r.get('/incidents/:id/severity',auth,(req,res)=>{const i=db().prepare('SELECT severity_score score,severity_level level,severity_factors factors,severity_reasons reasons,updated_at timestamp FROM incidents WHERE id=?').get(req.params.id) as any;if(!i)return res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'Incident not found'}});ok(res,{...i,factors:parseJson(i.factors,{}),reasons:parseJson(i.reasons,[])});});
r.post('/incidents/:id/severity/recalculate',auth,roles('COORDINATOR','ADMIN'),(req,res)=>ok(res,recomputeSeverity(String(req.params.id),z.record(z.string(),z.number()).parse(req.body.factors||{}),req.user!.id)));

r.post('/help-requests',auth,roles('RESIDENT','COORDINATOR','ADMIN'),(req,res)=>ok(res,createHelpRequest(req.user!.id,helpSchema.parse(req.body)),201));
r.get('/help-requests',auth,(req,res)=>{const privileged=['COORDINATOR','ADMIN'].includes(req.user!.role);const rows=privileged?db().prepare(`SELECT * FROM help_requests ${req.query.incidentId?'WHERE incident_id=?':''} ORDER BY priority_score DESC,created_at`).all(...(req.query.incidentId?[req.query.incidentId]:[])):db().prepare('SELECT * FROM help_requests WHERE resident_id=? ORDER BY created_at DESC').all(req.user!.id);ok(res,(rows as any[]).map(hydrateRequest));});
r.get('/help-requests/:id',auth,(req,res)=>{const x=db().prepare('SELECT * FROM help_requests WHERE id=?').get(req.params.id) as any;if(!x)return res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'Help request not found'}});const assigned=req.user!.role==='RESPONDER'&&db().prepare('SELECT 1 FROM assignments a JOIN responders r ON r.id=a.responder_id WHERE a.request_id=? AND r.user_id=?').get(x.id,req.user!.id);if(x.resident_id!==req.user!.id&&!['COORDINATOR','ADMIN'].includes(req.user!.role)&&!assigned)return res.status(403).json({success:false,error:{code:'FORBIDDEN',message:'Access denied'}});ok(res,hydrateRequest(x));});
r.post('/help-requests/:id/cancel',auth,(req,res)=>{const x=db().prepare('SELECT * FROM help_requests WHERE id=?').get(req.params.id) as any;if(!x)return res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'Request not found'}});if(x.resident_id!==req.user!.id&&!['COORDINATOR','ADMIN'].includes(req.user!.role))return res.status(403).json({success:false,error:{code:'FORBIDDEN',message:'Access denied'}});db().prepare("UPDATE help_requests SET status='CANCELLED',updated_at=? WHERE id=?").run(now(),x.id);audit('HELP_REQUEST_CANCELLED',{incidentId:x.incident_id,requestId:x.id,actorId:req.user!.id,previousState:x.status,newState:'CANCELLED'});ok(res,{id:x.id,status:'CANCELLED'});});
r.post('/safe-checkins',auth,(req,res)=>{const b=z.object({incidentId:z.string(),latitude:z.number().optional(),longitude:z.number().optional(),source:z.enum(['SELF','COORDINATOR','SHELTER']).default('SELF'),userId:z.string().optional()}).parse(req.body),userId=b.userId&&['COORDINATOR','ADMIN'].includes(req.user!.role)?b.userId:req.user!.id,t=now();db().prepare('INSERT INTO safe_checkins(id,user_id,incident_id,latitude,longitude,source,created_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(user_id,incident_id) DO UPDATE SET latitude=excluded.latitude,longitude=excluded.longitude,source=excluded.source,created_at=excluded.created_at').run(id('safe'),userId,b.incidentId,b.latitude??null,b.longitude??null,b.source,t);db().prepare("UPDATE users SET operational_status='SAFE',updated_at=? WHERE id=?").run(t,userId);db().prepare("UPDATE help_requests SET status='SAFE',updated_at=? WHERE resident_id=? AND incident_id=? AND status NOT IN ('CANCELLED','CLOSED')").run(t,userId,b.incidentId);audit('PERSON_SAFE',{incidentId:b.incidentId,actorId:req.user!.id,newState:'SAFE',latitude:b.latitude,longitude:b.longitude,metadata:{userId,source:b.source}});emit('person.safe',{userId,incidentId:b.incidentId,timestamp:t});ok(res,{userId,incidentId:b.incidentId,status:'SAFE',timestamp:t},201);});

r.post('/responders/availability',auth,roles('RESPONDER'),(req,res)=>{const b=z.object({available:z.boolean(),capabilities:z.array(z.enum(['TRANSPORT','MEDICAL_FIRST_AID','EVACUATION_ASSISTANCE','GENERAL_ASSISTANCE'])).default([]),skills:z.array(z.string()).default([]),vehicleAvailable:z.boolean().default(false),passengerCapacity:z.number().int().nonnegative().default(0),location:locationSchema.optional(),incidentId:z.string().optional()}).parse(req.body);const rp=db().prepare('SELECT * FROM responders WHERE user_id=?').get(req.user!.id) as any;if(!rp)return res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'Responder profile missing'}});if(rp.verification_status!=='VERIFIED'&&b.available)return res.status(403).json({success:false,error:{code:'NOT_VERIFIED',message:'Responder verification required'}});db().prepare('UPDATE responders SET availability=?,capabilities=?,skills=?,vehicle_available=?,passenger_capacity=?,current_incident_id=?,status=?,updated_at=? WHERE user_id=?').run(+b.available,JSON.stringify(b.capabilities),JSON.stringify(b.skills),+b.vehicleAvailable,b.passengerCapacity,b.incidentId||null,b.available?'AVAILABLE':'UNAVAILABLE',now(),req.user!.id);if(b.location){const l=b.location;db().prepare('INSERT INTO locations VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(id('loc'),req.user!.id,b.incidentId||null,null,l.latitude,l.longitude,l.accuracy??null,l.source,l.sharingState,l.sharingState==='SHARED'?'AVAILABLE':'NOT_SHARED',now());}audit('RESPONDER_AVAILABILITY_CHANGED',{actorId:req.user!.id,newState:b.available?'AVAILABLE':'UNAVAILABLE'});emit('responder.status_changed',{userId:req.user!.id,status:b.available?'AVAILABLE':'UNAVAILABLE'});ok(res,db().prepare('SELECT * FROM responders WHERE user_id=?').get(req.user!.id));});
r.get('/responders',auth,roles('COORDINATOR','ADMIN'),(_req,res)=>ok(res,db().prepare('SELECT r.*,u.name,u.email FROM responders r JOIN users u ON u.id=r.user_id').all().map(hydrateResponder)));
r.get('/matches/:requestId',auth,roles('COORDINATOR','ADMIN'),(req,res)=>ok(res,getMatches(String(req.params.requestId))));

r.post('/assignments',auth,roles('COORDINATOR','ADMIN'),(req,res)=>{const b=z.object({requestId:z.string(),responderId:z.string()}).parse(req.body),h=db().prepare('SELECT * FROM help_requests WHERE id=?').get(b.requestId) as any,rp=db().prepare('SELECT * FROM responders WHERE id=?').get(b.responderId) as any;if(!h||!rp)return res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'Request or responder not found'}});if(!rp.availability||rp.status!=='AVAILABLE'||rp.verification_status!=='VERIFIED')return res.status(409).json({success:false,error:{code:'RESPONDER_UNAVAILABLE',message:'Responder is not eligible'}});const t=now(),a={id:id('asn'),request_id:b.requestId,responder_id:b.responderId,status:'ASSIGNED',assigned_by:req.user!.id,assigned_at:t,updated_at:t};db().transaction(()=>{db().prepare('INSERT INTO assignments(id,request_id,responder_id,status,assigned_by,assigned_at,updated_at) VALUES(@id,@request_id,@responder_id,@status,@assigned_by,@assigned_at,@updated_at)').run(a);db().prepare("UPDATE help_requests SET status='ASSIGNED',updated_at=? WHERE id=?").run(t,b.requestId);db().prepare("UPDATE responders SET availability=0,status='BUSY',current_assignment_id=?,current_incident_id=?,updated_at=? WHERE id=?").run(a.id,h.incident_id,t,b.responderId);})();audit('RESPONDER_ASSIGNED',{incidentId:h.incident_id,requestId:h.id,assignmentId:a.id,actorId:req.user!.id,newState:'ASSIGNED'});notify(rp.user_id,h.incident_id,'RESPONDER_ASSIGNMENT','New rescue assignment',`You have been assigned request ${h.id}.`);emit('assignment.created',a);ok(res,a,201);});
r.get('/assignments',auth,(req,res)=>{let rows:any[]=[];if(['COORDINATOR','ADMIN'].includes(req.user!.role))rows=db().prepare('SELECT * FROM assignments ORDER BY updated_at DESC').all() as any[];else if(req.user!.role==='RESPONDER')rows=db().prepare('SELECT a.* FROM assignments a JOIN responders r ON r.id=a.responder_id WHERE r.user_id=? ORDER BY a.updated_at DESC').all(req.user!.id) as any[];else rows=db().prepare('SELECT a.* FROM assignments a JOIN help_requests h ON h.id=a.request_id WHERE h.resident_id=? ORDER BY a.updated_at DESC').all(req.user!.id) as any[];ok(res,rows);});
r.post('/assignments/:id/transition',auth,(req,res)=>{const b=z.object({status:z.enum(['ACCEPTED','REJECTED','EN_ROUTE','ARRIVED','ASSISTING','EVACUATED','SHELTER_CHECKIN','SAFE','COMPLETED','CLOSED','FAILED','CANCELLED','REASSIGNED']),reason:z.string().max(500).optional()}).parse(req.body),a=db().prepare('SELECT a.*,r.user_id responder_user_id FROM assignments a JOIN responders r ON r.id=a.responder_id WHERE a.id=?').get(req.params.id) as any;if(!a)return res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'Assignment not found'}});if(req.user!.role==='RESPONDER'&&a.responder_user_id!==req.user!.id)return res.status(403).json({success:false,error:{code:'FORBIDDEN',message:'Assignment belongs to another responder'}});if(req.user!.role==='RESIDENT')return res.status(403).json({success:false,error:{code:'FORBIDDEN',message:'Access denied'}});ok(res,transitionAssignment(String(req.params.id),b.status,req.user!.id,b.reason));});
r.post('/assignments/:id/reassign',auth,roles('COORDINATOR','ADMIN'),(req,res)=>{const assignmentId=String(req.params.id),b=z.object({responderId:z.string(),reason:z.string().optional()}).parse(req.body),old=db().prepare('SELECT request_id FROM assignments WHERE id=?').get(assignmentId) as any;if(!old)return res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'Assignment not found'}});const rp=db().prepare('SELECT * FROM responders WHERE id=?').get(b.responderId) as any;if(!rp||!rp.availability||rp.status!=='AVAILABLE')return res.status(409).json({success:false,error:{code:'RESPONDER_UNAVAILABLE',message:'Replacement responder is unavailable'}});transitionAssignment(assignmentId,'REASSIGNED',req.user!.id,b.reason||'Coordinator reassignment');const h=db().prepare('SELECT * FROM help_requests WHERE id=?').get(old.request_id) as any;const t=now(),a={id:id('asn'),request_id:old.request_id,responder_id:b.responderId,status:'ASSIGNED',assigned_by:req.user!.id,assigned_at:t,updated_at:t};db().transaction(()=>{db().prepare('INSERT INTO assignments(id,request_id,responder_id,status,assigned_by,assigned_at,updated_at) VALUES(@id,@request_id,@responder_id,@status,@assigned_by,@assigned_at,@updated_at)').run(a);db().prepare("UPDATE help_requests SET status='ASSIGNED',updated_at=? WHERE id=?").run(t,old.request_id);db().prepare("UPDATE responders SET availability=0,status='BUSY',current_assignment_id=?,current_incident_id=?,updated_at=? WHERE id=?").run(a.id,h.incident_id,t,b.responderId);})();audit('RESPONDER_REASSIGNED',{incidentId:h.incident_id,requestId:h.id,assignmentId:a.id,actorId:req.user!.id,newState:'ASSIGNED'});notify(rp.user_id,h.incident_id,'RESPONDER_ASSIGNMENT','New rescue assignment',`You have been assigned request ${h.id}.`);emit('assignment.created',a);ok(res,a,201);});

r.post('/shelters',auth,roles('COORDINATOR','ADMIN'),(req,res)=>{const b=z.object({incidentId:z.string().optional(),name:z.string(),latitude:z.number(),longitude:z.number(),capacity:z.number().int().positive(),occupancy:z.number().int().nonnegative().default(0),accessibility:z.boolean().default(false),services:z.array(z.string()).default([])}).parse(req.body),t=now(),s={id:id('shl'),incident_id:b.incidentId||null,name:b.name,latitude:b.latitude,longitude:b.longitude,capacity:b.capacity,occupancy:b.occupancy,status:b.occupancy>=b.capacity?'FULL':b.occupancy/b.capacity>=.8?'NEAR_CAPACITY':'OPEN',accessibility:+b.accessibility,services:JSON.stringify(b.services),created_at:t,updated_at:t};db().prepare('INSERT INTO shelters VALUES(@id,@incident_id,@name,@latitude,@longitude,@capacity,@occupancy,@status,@accessibility,@services,@created_at,@updated_at)').run(s);ok(res,{...s,services:b.services},201);});
r.get('/shelters',auth,(req,res)=>ok(res,(db().prepare(`SELECT * FROM shelters ${req.query.incidentId?'WHERE incident_id=?':''}`).all(...(req.query.incidentId?[req.query.incidentId]:[])) as any[]).map(x=>({...x,accessibility:!!x.accessibility,services:parseJson(x.services,[])}))));
r.post('/shelters/:id/checkins',auth,roles('RESPONDER','COORDINATOR','ADMIN'),(req,res)=>{const b=z.object({userId:z.string(),requestId:z.string().optional(),peopleCount:z.number().int().positive().default(1)}).parse(req.body),s=db().prepare('SELECT * FROM shelters WHERE id=?').get(req.params.id) as any;if(!s)return res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'Shelter not found'}});if(s.occupancy+b.peopleCount>s.capacity)return res.status(409).json({success:false,error:{code:'SHELTER_FULL',message:'Shelter capacity exceeded'}});const t=now(),c={id:id('chk'),shelter_id:s.id,user_id:b.userId,request_id:b.requestId||null,people_count:b.peopleCount,checked_in_by:req.user!.id,created_at:t};db().transaction(()=>{db().prepare('INSERT INTO shelter_checkins VALUES(@id,@shelter_id,@user_id,@request_id,@people_count,@checked_in_by,@created_at)').run(c);const occ=s.occupancy+b.peopleCount,status=occ>=s.capacity?'FULL':occ/s.capacity>=.8?'NEAR_CAPACITY':'OPEN';db().prepare('UPDATE shelters SET occupancy=?,status=?,updated_at=? WHERE id=?').run(occ,status,t,s.id);if(b.requestId)db().prepare("UPDATE help_requests SET status='SHELTER_CHECKIN',updated_at=? WHERE id=?").run(t,b.requestId);})();audit('SHELTER_CHECKIN',{incidentId:s.incident_id,requestId:b.requestId,actorId:req.user!.id,newState:'SHELTER_CHECKIN',metadata:{shelterId:s.id,userId:b.userId}});emit('shelter.status_changed',{shelterId:s.id,occupancy:s.occupancy+b.peopleCount});ok(res,c,201);});

r.post('/reports',auth,(req,res)=>{const b=z.object({incidentId:z.string(),latitude:z.number(),longitude:z.number(),category:z.enum(['BLOCKED_ROAD','SMOKE_FIRE','HAZARD','INFRASTRUCTURE_DAMAGE','SHELTER_ISSUE','OTHER']),description:z.string().min(3).max(1500)}).parse(req.body),t=now(),x={id:id('rpt'),incident_id:b.incidentId,reporter_id:req.user!.id,latitude:b.latitude,longitude:b.longitude,category:b.category,description:b.description,source_type:'COMMUNITY',verification_status:'UNVERIFIED',created_at:t,updated_at:t};db().prepare('INSERT INTO community_reports VALUES(@id,@incident_id,@reporter_id,@latitude,@longitude,@category,@description,@source_type,@verification_status,@created_at,@updated_at)').run(x);audit('COMMUNITY_REPORT_CREATED',{incidentId:b.incidentId,actorId:req.user!.id,latitude:b.latitude,longitude:b.longitude,metadata:{reportId:x.id,verificationStatus:'UNVERIFIED'}});ok(res,x,201);});
r.get('/reports',auth,(req,res)=>ok(res,db().prepare(`SELECT * FROM community_reports ${req.query.incidentId?'WHERE incident_id=?':''} ORDER BY created_at DESC`).all(...(req.query.incidentId?[req.query.incidentId]:[]))));
r.patch('/reports/:id/verification',auth,roles('COORDINATOR','ADMIN'),(req,res)=>{const b=z.object({status:z.enum(['VERIFIED','REJECTED'])}).parse(req.body);db().prepare('UPDATE community_reports SET verification_status=?,updated_at=? WHERE id=?').run(b.status,now(),req.params.id);audit('COMMUNITY_REPORT_VERIFICATION_CHANGED',{actorId:req.user!.id,newState:b.status,metadata:{reportId:req.params.id}});ok(res,db().prepare('SELECT * FROM community_reports WHERE id=?').get(req.params.id));});

r.get('/alerts',auth,(req,res)=>ok(res,db().prepare('SELECT * FROM notifications WHERE user_id=? OR user_id IS NULL ORDER BY created_at DESC').all(req.user!.id)));
r.post('/alerts/incidents/:id/generate',auth,roles('COORDINATOR','ADMIN'),(req,res)=>{const i=db().prepare('SELECT severity_level FROM incidents WHERE id=?').get(req.params.id) as any;if(!i)return res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'Incident not found'}});ok(res,{generated:createGeofenceAlerts(String(req.params.id),i.severity_level).length});});
r.post('/alerts/:id/read',auth,(req,res)=>{db().prepare('UPDATE notifications SET read_at=? WHERE id=? AND user_id=?').run(now(),req.params.id,req.user!.id);ok(res,{id:req.params.id,read:true});});

r.get('/escalations/recommend/:incidentId',auth,roles('COORDINATOR','ADMIN'),(req,res)=>ok(res,recommendEscalation(String(req.params.incidentId))));
r.post('/escalations',auth,roles('COORDINATOR','ADMIN'),(req,res)=>{const b=z.object({incidentId:z.string(),reason:z.string().min(3),recommendedLevel:z.enum(['COMMUNITY','NGO_TRAINED_RESPONDERS','PROFESSIONAL_EMERGENCY_RESPONSE','EMERGENCY_MANAGEMENT','HIGHER_LEVEL_AUTHORIZED_RESPONSE'])}).parse(req.body),t=now(),e={id:id('esc'),incident_id:b.incidentId,reason:b.reason,recommended_level:b.recommendedLevel,status:'PENDING_AUTHORIZATION',created_by:req.user!.id,approved_by:null,created_at:t,updated_at:t};db().prepare('INSERT INTO escalations VALUES(@id,@incident_id,@reason,@recommended_level,@status,@created_by,@approved_by,@created_at,@updated_at)').run(e);audit('ESCALATION_CREATED',{incidentId:b.incidentId,actorId:req.user!.id,newState:e.status,metadata:{level:b.recommendedLevel}});emit('escalation.created',e);ok(res,e,201);});
r.post('/escalations/:id/approve',auth,roles('COORDINATOR','ADMIN'),(req,res)=>{const e=db().prepare('SELECT * FROM escalations WHERE id=?').get(req.params.id) as any;if(!e)return res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'Escalation not found'}});db().prepare("UPDATE escalations SET status='APPROVED',approved_by=?,updated_at=? WHERE id=?").run(req.user!.id,now(),e.id);audit('ESCALATION_APPROVED',{incidentId:e.incident_id,actorId:req.user!.id,previousState:e.status,newState:'APPROVED'});ok(res,{...e,status:'APPROVED',approved_by:req.user!.id});});
r.get('/escalations',auth,roles('COORDINATOR','ADMIN'),(_req,res)=>ok(res,db().prepare('SELECT * FROM escalations ORDER BY created_at DESC').all()));

r.post('/fraud/scan/:userId',auth,roles('ADMIN'),(req,res)=>{const stats=db().prepare(`SELECT count(*) total,sum(CASE WHEN status='CANCELLED' THEN 1 ELSE 0 END) cancelled FROM help_requests WHERE resident_id=? AND created_at>=datetime('now','-24 hours')`).get(req.params.userId) as any;const reasons=[] as string[];if(stats.total>=8)reasons.push('Unusual request frequency');if(stats.cancelled>=4)reasons.push('Repeated cancelled requests');if(!reasons.length)return ok(res,{flagged:false});const t=now(),f={id:id('flg'),user_id:req.params.userId,request_id:null,incident_id:null,reason:reasons.join('; '),evidence_references:JSON.stringify([{type:'24h_request_stats',...stats}]),status:'OPEN',investigator_id:null,resolution:null,created_at:t,updated_at:t};db().prepare('INSERT INTO fraud_cases VALUES(@id,@user_id,@request_id,@incident_id,@reason,@evidence_references,@status,@investigator_id,@resolution,@created_at,@updated_at)').run(f);audit('FRAUD_FLAG_CREATED',{actorId:req.user!.id,metadata:{caseId:f.id,userId:f.user_id}});ok(res,{flagged:true,case:f},201);});
r.get('/fraud',auth,roles('ADMIN'),(_req,res)=>ok(res,db().prepare('SELECT * FROM fraud_cases ORDER BY created_at DESC').all()));
r.patch('/fraud/:id',auth,roles('ADMIN'),(req,res)=>{const b=z.object({status:z.enum(['OPEN','UNDER_REVIEW','RESOLVED','DISMISSED']),resolution:z.string().optional()}).parse(req.body);db().prepare('UPDATE fraud_cases SET status=?,resolution=?,investigator_id=?,updated_at=? WHERE id=?').run(b.status,b.resolution||null,req.user!.id,now(),req.params.id);ok(res,db().prepare('SELECT * FROM fraud_cases WHERE id=?').get(req.params.id));});
r.get('/audit',auth,roles('ADMIN'),(req,res)=>ok(res,db().prepare(`SELECT * FROM audit_logs WHERE (? IS NULL OR incident_id=?) AND (? IS NULL OR request_id=?) ORDER BY created_at DESC LIMIT 1000`).all(req.query.incidentId||null,req.query.incidentId||null,req.query.requestId||null,req.query.requestId||null)));
r.get('/audit/timeline/:requestId',auth,roles('COORDINATOR','ADMIN'),(req,res)=>ok(res,db().prepare('SELECT * FROM audit_logs WHERE request_id=? ORDER BY created_at').all(req.params.requestId)));

r.get('/analytics/incidents/:id',auth,roles('COORDINATOR','ADMIN'),(req,res)=>{const counts=db().prepare(`SELECT count(*) total,sum(CASE WHEN status IN ('SAFE','CLOSED') THEN 1 ELSE 0 END) completed,sum(CASE WHEN status NOT IN ('SAFE','CLOSED','CANCELLED') THEN 1 ELSE 0 END) unresolved FROM help_requests WHERE incident_id=?`).get(req.params.id) as any;const responders=db().prepare(`SELECT count(*) total,sum(availability) active FROM responders WHERE current_incident_id=? OR current_incident_id IS NULL`).get(req.params.id) as any;const shelters=db().prepare('SELECT coalesce(sum(occupancy),0) occupancy,coalesce(sum(capacity),0) capacity FROM shelters WHERE incident_id=?').get(req.params.id) as any;const escalations=(db().prepare('SELECT count(*) n FROM escalations WHERE incident_id=?').get(req.params.id) as any).n;const timings=db().prepare(`SELECT avg((julianday(a.accepted_at)-julianday(h.created_at))*86400) response_seconds,avg((julianday(a.assigned_at)-julianday(h.created_at))*86400) assignment_seconds FROM assignments a JOIN help_requests h ON h.id=a.request_id WHERE h.incident_id=?`).get(req.params.id);const trend=db().prepare("SELECT new_state score,created_at FROM audit_logs WHERE incident_id=? AND action='INCIDENT_SEVERITY_CHANGED' ORDER BY created_at").all(req.params.id);ok(res,{totalHelpRequests:counts.total,completedRequests:counts.completed||0,unresolvedRequests:counts.unresolved||0,averageResponseSeconds:(timings as any).response_seconds,averageAssignmentSeconds:(timings as any).assignment_seconds,responders:responders.total,activeResponders:responders.active||0,shelterUtilization:shelters.capacity?shelters.occupancy/shelters.capacity:0,escalationCount:escalations,severityTrend:trend});});
r.get('/admin/dashboard',auth,roles('COORDINATOR','ADMIN'),(_req,res)=>{const one=(sql:string)=>db().prepare(sql).get() as any;ok(res,{activeIncidents:one("SELECT count(*) n FROM incidents WHERE status IN ('DETECTED','ACTIVE')").n,overallSeverity:one("SELECT coalesce(max(severity_score),0) n FROM incidents WHERE status IN ('DETECTED','ACTIVE')").n,peopleNeedingHelp:one("SELECT coalesce(sum(people_count),0) n FROM help_requests WHERE status NOT IN ('SAFE','CLOSED','CANCELLED')").n,safePeople:one("SELECT count(*) n FROM users WHERE operational_status='SAFE'").n,activeResponders:one('SELECT count(*) n FROM responders WHERE availability=1').n,unresolvedRequests:one("SELECT count(*) n FROM help_requests WHERE status NOT IN ('SAFE','CLOSED','CANCELLED')").n,sheltersOpen:one("SELECT count(*) n FROM shelters WHERE status IN ('OPEN','NEAR_CAPACITY')").n,criticalRequests:one("SELECT count(*) n FROM help_requests WHERE priority_level='CRITICAL' AND status NOT IN ('SAFE','CLOSED','CANCELLED')").n});});

r.get('/providers/status',auth,roles('COORDINATOR','ADMIN'),asyncRoute(async(_req:any,res:any)=>{const [disaster,weather,alerts,shelters,roads]=await Promise.all([providers.disaster.fetchIncident(),providers.weather.fetchWeather(0,0),providers.alerts.fetchAlerts(),providers.shelters.fetchShelters(),providers.roads.fetchRoads()]);ok(res,{disaster,weather,alerts,shelters,roads});}));
r.post('/simulator/start',auth,roles('COORDINATOR','ADMIN'),asyncRoute(async(req:any,res:any)=>ok(res,await simulatorStart(z.object({latitude:z.number().optional(),longitude:z.number().optional(),initialRadius:z.number().positive().optional(),spreadSpeed:z.number().nonnegative().optional(),spreadDirection:z.number().optional(),severity:z.number().min(0).max(100).optional(),simulatedPopulation:z.number().int().nonnegative().optional(),windSpeed:z.number().nonnegative().optional(),windDirection:z.number().optional(),temperature:z.number().optional(),humidity:z.number().min(0).max(100).optional(),reports:z.number().int().nonnegative().optional(),responders:z.number().int().nonnegative().optional()}).parse(req.body),req.user!.id),201)));
r.post('/simulator/control',auth,roles('COORDINATOR','ADMIN'),(req,res)=>{const b=z.object({action:z.enum(['PAUSE','RESUME','RESET','INCREASE_SPREAD','INCREASE_SEVERITY','GENERATE_REPORTS','GENERATE_HELP_REQUESTS','GENERATE_RESPONDERS','TRIGGER_CRITICAL_STATE']),amount:z.number().optional(),count:z.number().int().positive().optional(),radiusIncrease:z.number().positive().optional()}).parse(req.body);ok(res,simulatorControl(b.action,req.user!.id,b));});
r.get('/simulator',auth,roles('COORDINATOR','ADMIN'),(_req,res)=>{const s=db().prepare("SELECT * FROM simulator_state WHERE id='primary'").get() as any;ok(res,s?{...s,config:parseJson(s.config,{})}:{status:'NOT_STARTED'});});
r.get('/health',(_req,res)=>{let database='up';try{db().prepare('SELECT 1').get();}catch{database='down';}res.status(database==='up'?200:503).json({success:database==='up',data:{service:'up',database,providers:{mockDisaster:'up',mockWeather:'up',mockAlerts:'up',mockShelters:'up',mockRoads:'up',mockAi:'up'},timestamp:now()}});});

function hydrateIncident(x:any){return {...x,severity_factors:parseJson(x.severity_factors,{}),severity_reasons:parseJson(x.severity_reasons,[]),boundary_json:parseJson(x.boundary_json,null)};}
function hydrateRequest(x:any){return {...x,medical_emergency:!!x.medical_emergency,immediate_danger:!!x.immediate_danger,vulnerabilities:parseJson(x.vulnerabilities,[]),priority_reasons:parseJson(x.priority_reasons,[])};}
function hydrateResponder(x:any){return {...x,availability:!!x.availability,vehicle_available:!!x.vehicle_available,skills:parseJson(x.skills,[]),capabilities:parseJson(x.capabilities,[])};}
export default r;
